### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by dyaeger** [irt-incognito/car-dealership#1]
`mvn package` fails to build project with the following output:

Are we missing something on our end?

Java version: 12.0.1 (do we need to use 11 specifically?)
Maven: 3.6.2

```
-------------------------------------------------------------------------------
Test set: com.homework.carsearch.controller.CarControllerTest
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in com.homework.carsearch.controller.CarControllerTest
findCarDelegates(com.homework.carsearch.controller.CarControllerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problem: 
	The declared package "com.homework.CarSearch.controller" does not match the expected package "com.homework.carsearch.controller"

	at com.homework.carsearch.controller.CarControllerTest.<init>(CarControllerTest.java:1)

findCarReturnsAllCarsWhenNoFiltersGiven(com.homework.carsearch.controller.CarControllerTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problem: 
	The declared package "com.homework.CarSearch.controller" does not match the expected package "com.homework.carsearch.controller"

	at com.homework.carsearch.controller.CarControllerTest.<init>(CarControllerTest.java:1)

createThrowsInternalServerError(com.homework.carsearch.controller.CarControllerTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problem: 
	The declared package "com.homework.CarSearch.controller" does not match the expected package "com.homework.carsearch.controller"

	at com.homework.carsearch.controller.CarControllerTest.<init>(CarControllerTest.java:1)

createCarDelegatesToRepository(com.homework.carsearch.controller.CarControllerTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problem: 
	The declared package "com.homework.CarSearch.controller" does not match the expected package "com.homework.carsearch.controller"

	at com.homework.carsearch.controller.CarControllerTest.<init>(CarControllerTest.java:1)

createThrowsBadRequestError(com.homework.carsearch.controller.CarControllerTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.Error: 
Unresolved compilation problem: 
	The declared package "com.homework.CarSearch.controller" does not match the expected package "com.homework.carsearch.controller"

	at com.homework.carsearch.controller.CarControllerTest.<init>(CarControllerTest.java:1)

```

```
# Created at 2019-10-01T10:54:23.670
java.lang.NoClassDefFoundError: com/homework/CarSearch/controller/CarControllerTest (wrong name: com/homework/carsearch/controller/CarControllerTest)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:136)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:100)
	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.setTestsToRun(JUnit4Provider.java:189)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:132)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by hiwhy** [comment]
Hi David, 

    The package is self contained. You shouldn't be missing anything. Any chance this could be fixed with a repull of the package? 

   I've pulled down the package on another computer and setup java 12.0.2-zulu with maven 3.6.2 and successfully able to run mvn package.

**Comment by dyaeger** [comment]
I was able to get the project to run. Will move to evaluating it shortly. Thanks for the response.
